project:
  type: website
  output-dir: docs

website:
  favicon: favicon.ico
  description: "Political Science World Cup Prediction Competition"
  site-url: https://haavas.github.io/VM2026/ # you must change this appropriately for RSS feeds to work properly
  title: "World Cup Competition 2026"
  navbar:
    logo: images/JulRim.jpg
    right:
      - about.qmd
      - rules.qmd
      - past_winners.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



