{
  "hash": "51122a2d873accfa66298e8292af112a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Vinner demokratier på fotballbanen?\"\nsubtitle: \"En statistisk analyse av mål og regime i VM 1994–2022\"\nauthor: \"Håvard Strand\"\ndate: \"2026-04-26\"\ncategories: [analyse, metode, demokrati]\nformat:\n  html:\n    toc: true\n    toc-title: \"Innhold\"\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nFotball er enkel sport: det handler om å score mål. Men bak hvert mål ligger tiår med investering, talentutvikling og organisering. Er det noen sammenheng mellom landets politiske system og hvor mange mål laget scorer i VM? Det er spørsmålet vi ser på her — ikke fordi vi forventer et dramatisk svar, men fordi veien til svaret tvinger oss til å ta stilling til noen interessante metodiske valg.\n\n## Data og design\n\nVi bruker kampdata fra åtte VM-sluttspill, fra USA 1994 til Qatar 2022 — totalt 626 kamper og 1252 lags-observasjoner i analysen. Målscoren er registrert etter 90 (eventuelt 120) minutter; straffekonkurranser er ekskludert.\n\nTre kovariater knyttes til hvert lag, hentet fra tre separate kilder:\n\n- **FIFA-ranglistepoengsummen** like før turneringen starter (fra Kaggle-datasett med historiske ranglister)\n- **Befolkningsstørrelse** (log-transformert, fra Verdensbanken via `WDI`)\n- **V-Dem Liberal Democracy Index** — et komposittmål for liberalt demokrati som strekker seg fra 0 (minst demokratisk) til 1 (mest demokratisk), fra Varieties of Democracy-prosjektet\n\nI tillegg kontrollerer vi for om laget spilte *hjemme som vertsnasjon* og om kampen var en *sluttspillkamp* (fremfor gruppespillskamp).\n\nUtfallet modelleres som en tellevariabel (antall mål scored av ett lag i én kamp), noe som gjør Poisson-regresjon til et naturlig valg.\n\n## Hva gjør tilfeldig effekt — og hva skjer uten den?\n\n### Problemet: avhengige observasjoner\n\nStandard Poisson-regresjon antar at hver observasjon er trukket uavhengig. For oss betyr det at antall mål Brazil scorer, er uavhengig av antall mål som scores mot dem i den samme kampen. Det er åpenbart feil.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Hjemmelagets og bortelagets målscorer i de samme kampene. Den positive sammenhengen viser at høymålskamper er høymålskamper for begge lag — ikke bare for det ene.](index_files/figure-html/fig-korrelasjon-1.png){#fig-korrelasjon width=576}\n:::\n:::\n\n\nKorrelasjonen er -0.13. Det er ikke stor, men den er konsistent og ikke tilfeldig: det er noe *ved selve kampen* — dommeren, banen, det taktiske opplegget til begge lag, et åpent tempo — som enten fremmer eller hemmer mål for *begge* lag simultant.\n\nKamp-til-kamp-variasjonen skyldes faktorer som ingen av kovariatene våre fanger. Når vi later som om de to halvdelene av kampen er uavhengige, forteller vi modellen at vi har mer informasjon enn vi egentlig har.\n\n### Modellene side om side\n\nTo modeller, bare én linje forskjell:\n\n$$\n\\underbrace{\\log(\\mu_{ij}) = \\beta_0 + \\mathbf{x}_{ij}^\\top \\boldsymbol{\\beta}}_{\\text{uten tilfeldig effekt}}\n\\qquad\\qquad\n\\underbrace{\\log(\\mu_{ij}) = \\beta_0 + \\mathbf{x}_{ij}^\\top \\boldsymbol{\\beta} + u_j}_{\\text{med tilfeldig effekt}}\n$$\n\nder $u_j \\sim \\mathcal{N}(0,\\,\\sigma^2)$.\n\n$u_j$ er en kampspesifikk \"mål-vennlighet\" — ett tall per kamp, lik for begge lagene i kamp $j$. Det er ikke en parameter vi estimerer for å tolke direkte: vi integrerer den bort matematisk og lar $\\sigma^2$ oppsummere *hvor mye* kampspesifikk variasjon som eksisterer.\n\nNøkkelforskjellen: $u_j$ er *delt mellom de to lagene i samme kamp*. Det betyr at de to observasjonene i en kamp er *betinget uavhengige* gitt $u_j$, men *marginalt korrelerte*. Modellen vet at begge halvdelene av kampen bærer fingeravtrykket av den samme kampen.\n\n### Hva $\\sigma^2$ forteller oss\n\n\n::: {.cell}\n\n:::\n\n\nDen estimerte standardavviket for de kampspesifikke interceptene er $\\hat\\sigma =$ 0.12. Hva betyr det konkret?\n\nEn kamp som ligger *ett standardavvik over* gjennomsnittet i \"mål-vennlighet\" ($u_j = \\hat\\sigma$) produserer 1.13 ganger så mange mål som en gjennomsnittskamp, alt annet likt. Det tilsvarer at begge lag scorer omtrent 1.13× det modellen ellers ville forutsagt basert på lagkvalitet alene. Kamper ett standardavvik *under* gjennomsnittet produserer tilsvarende $1/1.13 \\approx 0.88$ × av det forventede.\n\n### Konsekvenser for inferens: hva skjer uten?\n\nNår modellen uten tilfeldig effekt ser 1252 observasjoner, behandler den dem som 1252 uavhengige datapunkter. Men halvparten av dem er paret innen kamper. Effektiv informasjon er et sted mellom 626 (perfekt korrelasjon) og 1252 (ingen korrelasjon).\n\nKonsekvensen er at modellen uten tilfeldig effekt *underestimerer standardfeilene* — konfidensintervallene blir for smale og p-verdiene for lave. Vi tror vi vet mer enn vi gjør.\n\nFiguren under sammenligner konfidensintervallene fra de to modellene:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Konfidensintervaller (95 %) for de faste effektene: modell med random intercept (lilla) mot modell uten (grå). Estimatene er nesten identiske, men modellen uten tilfeldig effekt gir systematisk smalere intervaller.](index_files/figure-html/fig-se-sammenligning-1.png){#fig-se-sammenligning width=720}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nMedianen for KI-bredden er 1.01× bredere i modellen med tilfeldig effekt enn uten. Punktestimatene er nesten identiske — det er ikke *hva* modellen tror effektene er som endrer seg, men *hvor sikker* den er.\n\nDet er det klassiske resultatet ved klyngede data: å ignorere klyngestrukturen gir ikke nødvendigvis skjeve estimater, men det gir for mye tillit til dem.\n\n### En kort merknad om tolkning\n\nTilfeldig-effekt-modellen gir oss koeffisienter som beskriver hva som skjer *innenfor en gitt kamp* — betinget på $u_j$. Spørsmålet besvart er: \"Gitt at vi allerede vet kampens mål-vennlighet, hva er effekten av FIFA-poengsum?\"\n\nEn modell uten tilfeldig effekt gir *marginale* koeffisienter: effekten gjennomsnittlig over alle kamper, uten å kontrollere for kampspesifikk variasjon. For de fleste formål er den betingede tolkningen den rette — vi vil vite hva som skiller lag fra hverandre, ikke hva som skiller kamper.\n\n## Modellresultater\n\nVi estimerer to modellvarianter. Den *begrensede modellen* bruker differansen mellom laget og motstanderen for hver kovariat (dvs. $\\text{FIFA}_{lag} - \\text{FIFA}_{motstander}$), noe som tvinger frem en symmetriantagelse: en enhet FIFA-poeng opp hos ditt lag gir nøyaktig samme effekt som én enhet ned hos motstanderen. Den *fulle modellen* lar de to sidene ha egne koeffisienter.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Eksponentierte koeffisienter fra Poisson mixed model (fulle modellen). Verdier over 1 øker forventet antall mål, verdier under 1 reduserer det. Horisontale linjer viser 95 % konfidensintervall.](index_files/figure-html/fig-koeffisienter-1.png){#fig-koeffisienter width=672}\n:::\n:::\n\n\n\n::: {#tbl-koeffisienter .cell tbl-cap='Poisson mixed model — eksponentierte koeffisienter (rate ratios) med 95 % KI'}\n::: {.cell-output-display}\n\n\n|Variabel                    | Rate ratio| 95 % KI (nedre)| 95 % KI (øvre)| p-verdi|\n|:---------------------------|----------:|---------------:|--------------:|-------:|\n|FIFA (eget lag)             |      1.001|           1.000|          1.001| < 0.001|\n|FIFA (motstander)           |      0.999|           0.999|          1.000| < 0.001|\n|log befolkning (eget lag)   |      1.082|           1.038|          1.128| < 0.001|\n|log befolkning (motstander) |      0.947|           0.910|          0.986|   0.008|\n|V-Dem LDI (eget lag)        |      1.601|           1.266|          2.026| < 0.001|\n|V-Dem LDI (motstander)      |      0.595|           0.487|          0.727| < 0.001|\n|Vertsnasjon                 |      1.102|           0.819|          1.482|   0.522|\n|Sluttspillkamp              |      1.047|           0.931|          1.178|   0.445|\n\n\n:::\n:::\n\n\nSom ventet er **FIFA-ranglistepoengsummen** den klart sterkeste prediktoren. Et lag med høy FIFA-poengsum scorer mer — og møter de et lag med høy FIFA-sum er effekten motsatt. Alt dette er fornuftig: FIFA-ranglisten er designet for å oppsummere akkurat den informasjonen.\n\n**Sluttspillkamper** produserer litt færre mål. Det er også som forventet: lag spiller mer defensivt når et tap er terminalt.\n\n**Vertsnasjon-fordelen** er positiv, men usikker.\n\n### FIFA-ranglistens effekt i detalj\n\nFiguren under viser hvordan forventet antall mål endrer seg når FIFA-poengsummen varierer for *eget lag* (blå linje) og for *motstanderen* (rød linje), mens den andre siden holdes konstant på medianen.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Forventet antall mål som funksjon av FIFA-poengsum, separat for eget lag og motstander. Den andre sidens FIFA-poengsum er holdt konstant på medianen. Bånd viser 95 % KI.](index_files/figure-html/fig-fifa-1.png){#fig-fifa width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nMerk at koeffisienten opererer på enkeltpoeng i FIFA-ranglisten. Én enkelt poeng gjør svært lite — det interessante er hva som skjer over *hundre* poeng, som er et realistisk sprang mellom to lag i samme VM. Et hundre poengs fordel tilsvarer omtrent 6.2&nbsp;% flere forventede mål, holdt alt annet konstant.\n\nDe to linjene er omtrent speilbilder av hverandre. Det er en forutsetning modellen *ikke* tvinger frem: vi lar eget lag og motstanderens FIFA-koeffisient være frie. At de er tilnærmet symmetriske er et empirisk resultat og støtter antagelsen i den begrensede differansemodellen.\n\n## Demokrativariabelen i fokus\n\nNå til det vi egentlig ville vite: betyr det noe om laget kommer fra et demokrati?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Forventet antall mål som funksjon av V-Dem Liberal Democracy Index for eget lag, med motstanderen holdt på medianen. Grå bånd er 95 % prediksjonsintervall for den faste delen av modellen.](index_files/figure-html/fig-demokrati-1.png){#fig-demokrati width=672}\n:::\n:::\n\n\nI Poisson-modellen er koeffisientene på log-skalaen. Den eksponentierte koeffisienten er en *rate ratio*: den forteller hvor mange ganger forventet antall mål endres når prediktoren øker med én enhet.\n\nFor V-Dem LDI betyr dette: én enhets økning i demokratiindeksen (fra 0 til 1, dvs. fra det minst til det mest demokratiske) multipliserer forventet målscoring med den eksponentierte koeffisienten. Siden V-Dem går fra 0 til 1, er dette en fullstendig gjennomgang av skalaen — fra Qatar til Norge.\n\n\n::: {.cell}\n\n:::\n\n\nRate ratio for V-Dem LDI (eget lag) er **1.601** (95 % KI: 1.266–2.026, p = < 0.001).\n\nHva betyr dette i praksis? Sammenlign to lag med identisk FIFA-rangering og befolkningsstørrelse, men der det ene laget er et fullt demokrati (V-Dem ≈ 0.85, som Norge eller Sverige) og det andre er et autoritært regime (V-Dem ≈ 0.15, som Saudi-Arabia eller Kina). Ifølge modellen scorer det demokratiske laget omtrent 60&nbsp;% flere mål enn det autoritære — alt annet likt.\n\nMen \"alt annet likt\" er det viktige forbeholdet. FIFA-ranglisten fanger allerede mye av den informasjonen som er relevant for kampkvalitet: treningsfasiliteter, forbundskvalitet, spillerbase. Demokrativariabelen spiller en rolle *utover* det FIFA-ranglisten allerede fanger, men det er et smalere spørsmål enn \"er demokratier bedre til fotball?\"\n\n### Hva kan forklare effekten?\n\nDet er minst tre mekanismer som kan gi en sammenheng mellom demokrati og VM-mål:\n\n1. **Talentdistribusjon**: I mer åpne samfunn er det lettere for barn fra alle bakgrunner å bli oppdaget og utviklet. Autoritære regimer kanaliserer ressurser sentralt, men mister bredden.\n2. **Institusjonell autonomi**: Demokratiske fotballforbund opererer gjerne med mer institusjonell uavhengighet fra politisk press. Trenervalgene gjøres av sportsfolk, ikke politikere.\n3. **Spuriøs samvariasjon**: Demokrati korrelerer med BNP, humankapital og stabilt styresett — faktorer som alle kan påvirke fotballkvalitet, men som vi ikke fullt ut kontrollerer for.\n\nModellen kan ikke skille mellom disse forklaringene. Det vi kan si er at effekten, *gitt FIFA-poengsum og befolkningsstørrelse*, er statistisk signifikant.\n\n## Begrensninger\n\nEt par åpenbare forbehold:\n\n**Seleksjonsskjevhet**: Bare lag som kvalifiserer seg til VM inngår. Svake diktaturer (og svake demokratier) er sjeldnere representert. Vi ser på regimet blant de beste lagene i verden, ikke blant alle lag.\n\n**FIFA-ranglisten absorberer mye**: Ranglisten er oppdatert like før turneringen og reflekterer allerede lagets form og organisering. Demokrativariabelen konkurrerer om variasjon med en meget presis prediktor.\n\n**Effekter over tid**: V-Dem-indeksen varierer ikke bare på tvers av land, men også over tid. Saudi-Arabia i 1994 og Saudi-Arabia i 2022 er ulike. Modellen behandler alle år likt.\n\n## Oppsummering\n\n| | |\n|---|---|\n| **Modell** | Poisson mixed model med kampspesifikk random intercept |\n| **Sample** | VM 1994–2022, 626 kamper, 1252 observasjoner |\n| **Sterkeste prediktor** | FIFA-rangliste (som forventet) |\n| **Demokratieffekt** | Rate ratio 1.601 (V-Dem LDI, eget lag) |\n| **Random intercept** | Fanger kampspesifikk mål-vennlighet; håndterer korrelasjon innen kamp |\n\nDen tilfeldig effekten er ikke bare statistisk støy — den er et substansielt grep for å anerkjenne at to halvdeler av en kamp ikke er uavhengige. Og demokrativariabelen? Den sier noe interessant, men neppe noe avgjørende, om hva som gjør et VM-lag godt. Til VM 2026 vil det uansett være FIFA-poengsummen som teller mest.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}